baseURL = 'https://robbiesri.github.io/'
title = 'Render Chef'
theme = 'risotto'
copyright = "© Robert Srinivasiah."
languageCode = "en"
DefaultContentLanguage = "en"

[markup.goldmark.renderer]
unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
    